#*是否开启API服务端
enabled: false
#*是否开启dev模式
dev: false
#*是否为CDN,内网穿透等
cdn: false
#*API服务端地址
host: "0.0.0.0"
#*API自定义域名
apidomain: "localhost"
#*啟動服務器的端口號
port: 1941
#*默认日志等级
loglevel: "info"
##*Redis配置*
#*Redis地址
redisHost: ""
#*Redis端口
redisPort: ""
#*Redis用户名
redisUsername: ""
#*Redis密码
redisPassword: ""
#*Redis数据库
redisDB: 2
#*API署名
apiby: 'MapleLeaf'
#*是否啟用 HTTPS
httpsenabled: false
#*统计过期时间
redisExpire: 0 #*单位为秒,0表示永不过期
#*HTTPS 证书和私钥文件路径
httpskey: "private-key.pem"
httpscert: "certificate.pem"
#*是否開啟CORS跨域,開啟後,服务器会自动添加 Access-Control-Allow-Origin 头
#* "*"表示允许所有来源访问,可以指定具体的 URL，例如 http://example.com
corsenabled: true
corsorigin: "*"
#*请求速率限制
#*默認每 60 秒最多允许一个 IP 发送 100 次请求
rateLimitwindowMs: 60000 #*时间窗口，单位为毫秒
rateLimitmax: 100 #*每秒最大请求数
#*鉴权token
token: ""
#*鉴权在时间窗口内最大失败次数
maxFailAttempts: 5
#*鉴权时间窗口
timeWindow: 600000 #*单位为毫秒
#*黑名单 IP 列表
blacklistedIPs: []
#*白名单 IP 列表
whitelistedIPs: []

blackApiList:
  - /mail/send
