#*是否开启API服务端
enabled: false
#*API服务端地址
host: "0.0.0.0"
#*API自定义域名
apidomain: "localhost"
#*啟動服務器的端口號
port: 1129
#*默认日志等级
loglevel: "info"
##*Redis配置*
#*Redis地址
redisHost: ""
#*Redis端口
redisPort:
#*Redis用户名
redisUsername: ""
#*Redis密码
redisPassword: ""
#*Redis数据库
redisDB: 0
#*API署名
apiby: 'MapleLeaf'
#*是否啟用 HTTPS
httpsenabled: false
#*统计过期时间
redisExpire: 0 #*单位为秒,0表示永不过期
#*HTTPS 证书和私钥文件路径
httpskey: "private-key.pem"
httpscert: "certificate.pem"
#*是否開啟CORS跨域,開啟後,服务器会自动添加 Access-Control-Allow-Origin 头
#* "*"表示允许所有来源访问,可以指定具体的 URL，例如 http://example.com
corsenabled: true
corsorigin: "*"
#*请求速率限制
#*默認每 60 秒最多允许一个 IP 发送 100 次请求
rateLimitwindowMs: 60000 #*时间窗口，单位为毫秒
rateLimitmax: 100 #*每秒最大请求数
#*鉴权token
token: "为什么不玩原神"
#*鉴权在时间窗口内最大失败次数
maxFailAttempts: 5
#*鉴权时间窗口
timeWindow: 600000 #*单位为毫秒
#*黑名单 IP 列表
blacklistedIPs: []
#*白名单 IP 列表
whitelistedIPs: []

apiList:
  - name: '健康检查'
    path: '/health'
    method: 'GET'
    description: '检查API服务是否正常运行'
    authentication: false
  - name: '访问数据'
    path: '/stats'
    method: 'GET'
    description: '获取API访问统计数据'
    authentication: true
  - name: 'B站热榜'
    path: '/bilibili/hot'
    method: 'GET'
    description: '获取BiliBili热榜'
    authentication: false
  - name: 'Steam热榜'
    path: '/steam/hot'
    method: 'GET'
    description: '获取Steam热榜'
    authentication: false
  - name: 'Whois查询'
    path: '/webtool/whois'
    key:
      - name: 'domain'
        type: 'string'
        required: true
        description: '要查询的域名'
    method: 'GET'
    description: '获取域名的Whois信息'
    authentication: false
  - name: 'ICP备案查询'
    path: '/webtool/icp'
    key:
      - name: 'domain'
        type: 'string'
        required: true
        description: '要查询的域名'
    method: 'GET'
    description: '获取域名的ICP备案信息'
    authentication: false
  - name: 'SEO查询'
    path: '/webtool/seo'
    key:
      - name: 'url'
        type: 'string'
        required: true
        description: '要查询的链接'
    method: 'GET'
    description: '获取链接的SEO信息'
    authentication: false
  - name: '游戏搜索'
    path: '/search/game'
    key:
      - name: 'key'
        type: 'string'
        required: true
        description: '游戏关键词'
    method: 'GET'
    description: '搜索单机破解游戏'
    authentication: false
  - name: '磁力搜索'
    path: '/search/cili'
    key:
      - name: 'key'
        type: 'string'
        required: true
        description: '磁力搜索关键词'
    method: 'GET'
    description: '搜索磁力资源'
    authentication: false
  - name: '随机一言'
    path: '/one/yiyan'
    key:
      - name: 'type'
        type: 'string'
        required: false
        description: '类型，可选：json、text'
    method: 'GET'
    description: '获取随机一言'
    authentication: false