text:
  - name: `一言`
    reg: `/^#?(随机)?一言$/i`
    url: `http://127.0.0.1:${port}/one/yiyan?type=text`
text_json:
  - name: `一言`
    reg: `/^#?(随机)?二言$/i`
    data: `data.data`
    url: `http://127.0.0.1:${port}/one/yiyan?type=json`
image:
  - name: ``
    reg: ``
    url: ``
json_image:
  - name: ``
    reg: ``
    url: ``
record:
  - name: ``
    reg: ``
    url: ``
json_record:
  - name: ``
    reg: ``
    url: ``
video:
  - name: ``
    reg: ``
    url: ``
json_video:
  - name: ``
    reg: ``
    url: ``